name: rag-project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - cxx-compiler
  - cmake
  - setuptools
  - pip:
      - numpy>=2.0.0
      - torch>=2.4.1
      - torchvision>=0.19.1
      - docling
      - streamlit
      - sentence-transformers
      - requests
      - pymupdf
      - pandas
