name: rag-project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pymupdf
  - pip
  - cxx-compiler
  - cmake
  - setuptools
  - numpy=1.26.4  # 1.26.4 is the version that works with docling
  - requests
  - pip:
      - streamlit
      - docling